### ISSUE TITLE
Install not successful

### ISSUE THREAD

**Issue by herbertrivera** [Publish3r/smart-dns-proxy#2]
./build.sh:
checking OS compatibility...done.
checking if cURL is installed...done.
checking if Docker is installed...done.
checking if sudo is installed...done.
checking if dig is installed...done.
testing available ports...done.
disabling ufw...done.
installing net-tools...done.
log diagnostics info...build=0 client=24.187.117.131 local=64.31.55.37 public=64.31.55.37
done.
authorising clientip=24.187.117.131 on iface=eth0...done.
adding IPv4 iptables rules...done.
adding IPv6 iptables rules...done.
creating Docker and sniproxy configuration templates...done.
disabling Docker iptables control...done.
configuring sniproxy and Docker...done.
installing iptables|netfilter-persistent service...done.
saving iptables rules...done.
creating dnsmasq.conf from template...done.
updating dnsmasq.conf extip=64.31.55.37...done.
installing Python3 and requirements...failed.
configuring admin backend...Traceback (most recent call last):
  File "/opt/smart-dns-proxy/auth/pbkdf2_sha256_hash.py", line 4, in <module>
    from passlib.hash import pbkdf2_sha256
ModuleNotFoundError: No module named 'passlib'
Traceback (most recent call last):
  File "/opt/smart-dns-proxy/auth/pbkdf2_sha256_hash.py", line 4, in <module>
    from passlib.hash import pbkdf2_sha256
ModuleNotFoundError: No module named 'passlib'
done.
configuring admin frontend...done.
creating cron scripts...done.
pulling Docker containers...
root@dns:/opt/smart-dns-proxy

NOT WORKING. DOES NOT PROVIDE ADMIN USERNAME AND PASSWORD AND SITE NOT LOADING.

**Comment by ashmodai6** [comment]
Replace in the build.sh script all references to ${docker-compose) by docker compose
In two words

**Comment by herbertrivera** [comment]
hi, 
I changed it and still the same.
***@***.***:/opt/smart-dns-proxy# ./build.sh./build.sh: * checking OS compatibility...                                                                                  [ OK ] * checking if cURL is installed...                                                                              [ OK ] * checking if Docker is installed...                                                                            [ OK ] * checking if sudo is installed...                                                                              [ OK ] * checking if dig is installed...                                                                               [ OK ] * testing available ports...                                                                                    [ OK ] * disabling ufw...                                                                                              [ OK ] * installing net-tools...                                                                                       [ OK ] * log diagnostics info...                                                                                              build=0 client=24.187.117.131 local=64.31.55.37 public=64.31.55.37                                                                                                                 [ OK ] * authorising clientip=24.187.117.131 on iface=eth0...                                                          [ OK ] * adding IPv4 iptables rules...                                                                                 [ OK ] * adding IPv6 iptables rules...                                                                                 [ OK ] * creating Docker and sniproxy configuration templates...                                                       [ OK ] * disabling Docker iptables control...                                                                          [ OK ] * configuring sniproxy and Docker...                                                                            [ OK ] * installing iptables|netfilter-persistent service...                                                           [ OK ] * saving iptables rules...                                                                                      [ OK ] * creating dnsmasq.conf from template...                                                                        [ OK ] * updating dnsmasq.conf extip=64.31.55.37...                                                                    [ OK ] * installing Python3 and requirements...                                                                        [ OK ] * configuring admin backend...                                                                                  [ OK ] * configuring admin frontend...                                                                                 [ OK ] * creating cron scripts...                                                                                      [ OK ] * pulling Docker containers...                                                                                        ***@***.***:/opt/smart-dns-proxy#


Attached is the build.sh
Please advise.
Thanks

    On Thursday, January 4, 2024 at 02:18:20 PM EST, ashmodai6 ***@***.***> wrote:  
 
 


Replace in the build.sh script all references to ${docker-compose) by docker compose
In two words

**Comment by ashmodai6** [comment]
I don t see your file but what I was telling is to replace all reference to:
sudo $(which docker-compose)
by
sudo docker compose
this worked for me at least to get it installed

**Comment by herbertrivera** [comment]
Ok so change it to sudo docker compose instead of sudo $ (which docker-compose) as stated on your previous step? What I did was sudo $ (which docker compose) as stated on initial response.I will try it later when I get home.Thank you.HerbertSent from my iPhoneOn Jan 4, 2024, at 5:59 PM, Herbert Rivera ***@***.***> wrote:﻿
        hi, I changed it and still the ***@***.***:/opt/smart-dns-proxy# ./build.sh./build.sh: * checking OS compatibility...                                                                                  [ OK ] * checking if cURL is installed...                                                                              [ OK ] * checking if Docker is installed...                                                                            [ OK ] * checking if sudo is installed...                                                                              [ OK ] * checking if dig is installed...                                                                               [ OK ] * testing available ports...                                                                                    [ OK ] * disabling ufw...                                                                                              [ OK ] * installing net-tools...                                                                                       [ OK ] * log diagnostics info...                                                                                              build=0 client=24.187.117.131 local=64.31.55.37 public=64.31.55.37                                                                                                                 [ OK ] * authorising clientip=24.187.117.131 on iface=eth0...                                                          [ OK ] * adding IPv4 iptables rules...                                                                                 [ OK ] * adding IPv6 iptables rules...                                                                                 [ OK ] * creating Docker and sniproxy configuration templates...                                                       [ OK ] * disabling Docker iptables control...                                                                          [ OK ] * configuring sniproxy and Docker...                                                                            [ OK ] * installing iptables|netfilter-persistent service...                                                           [ OK ] * saving iptables rules...                                                                                      [ OK ] * creating dnsmasq.conf from template...                                                                        [ OK ] * updating dnsmasq.conf extip=64.31.55.37...                                                                    [ OK ] * installing Python3 and requirements...                                                                        [ OK ] * configuring admin backend...                                                                                  [ OK ] * configuring admin frontend...                                                                                 [ OK ] * creating cron scripts...                                                                                      [ OK ] * pulling Docker containers...                                                                                        ***@***.***:/opt/smart-dns-proxy#Attached is the build.shPlease advise.Thanks
        
        
            
                
                
                    On Thursday, January 4, 2024 at 02:18:20 PM EST, ashmodai6 ***@***.***> wrote:
                
                
                
                
Replace in the build.sh script all references to ${docker-compose) by docker compose
In two words

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

            
        <build.sh>

**Comment by herbertrivera** [comment]
> I don t see your file but what I was telling is to replace all reference to: sudo $(which docker-compose) by sudo docker compose this worked for me at least to get it installed

Ok so change it to sudo docker compose instead of sudo $ (which docker-compose) as stated on your previous step? What I did was sudo $ (which docker compose) as stated on initial response.

I will try it later when I get home.

Thank you.
Herbert

**Comment by herbertrivera** [comment]
done.
authorising clientip=97.133.84.31 on iface=eth0...done.
adding IPv4 iptables rules...done.
adding IPv6 iptables rules...done.
creating Docker and sniproxy configuration templates...done.
disabling Docker iptables control...done.
configuring sniproxy and Docker...done.
installing iptables|netfilter-persistent service...done.
saving iptables rules...done.
creating dnsmasq.conf from template...done.
updating dnsmasq.conf extip=64.31.55.37...done.
installing Python3 and requirements...done.
configuring admin backend...done.
configuring admin frontend...done.
creating cron scripts...done.
pulling Docker containers...done.
creating and starting Docker containers...done.
configuring init system...done.
reloading ipables rules...done.
testing DNS...done.
testing proxy (cURL)...done.

netflix-proxy-admin site=http://64.31.55.37:8080/ credentials=admin:2fa4b80At
testing netflix-proxy admin site...failed.
WARNING: IPv6=Disabled
Change your DNS to 64.31.55.37 and start watching Netflix out of region.
Note: get http://unzoner.com if your app/service no longer works with DNS based solutions.
Done.
root@dns:/opt/smart-dns-proxy#


ALSO ADMIN SITE ERROR 502

**Comment by herbertrivera** [comment]
![error2](https://github.com/Publish3r/smart-dns-proxy/assets/64083680/4a4d96ff-a380-46f5-907b-a2b9e1ff901c)
![error](https://github.com/Publish3r/smart-dns-proxy/assets/64083680/38f21a34-72fc-4711-b3f3-dd3b24ea9c00)

these are the errors.

**Comment by herbertrivera** [comment]
any update?

**Comment by Publish3r** [comment]
Try to change https://github.com/Publish3r/smart-dns-proxy/blob/main/auth/requirements.txt

dnspython
web.py
passlib

I can't test myself, i have no free VPS.

If anyone can fix all errors, please make a pull request or write here what you have changed.

Note: This is a very old fork from https://github.com/ab77/netflix-proxy - last update was over 2 years and some dependencies has changed.

**Comment by herbertrivera** [comment]
It worked. Thank you.

    On Friday, January 26, 2024 at 07:49:30 PM EST, Publish3r ***@***.***> wrote:  
 
 


Try to change https://github.com/Publish3r/smart-dns-proxy/blob/main/auth/requirements.txt

dnspython
web.py
passlib

I can't test myself, i have no free VPS.

If anyone can fix all errors, please make a pull request or write here what you have changed.

Note: This is a very old fork from https://github.com/ab77/netflix-proxy - last update was over 2 years and some dependencies has changed.

**Comment by Publish3r** [comment]
[herbertrivera](https://github.com/herbertrivera) Can you please provide me the working changed files? You can upload them anywhere in the internet. Mabey here https://www.filemail.com/ or any other site.
After that i can fix the Repo.
Thank you.

**Comment by Publish3r** [comment]
And on what OS you got it working? I tried on a Hetzner Ubuntu 22.04 VPS today and it doesn't work.
Changed:
install.sh:
sudo $(which docker-compose) by sudo docker compose
and auth/reqirements.txt:
dnspython
web.py
passlib


ModuleNotFoundError: No module named 'passlib'

**Comment by Publish3r** [comment]
The most Provider doesn't offer Ubuntu 18 anymore. I think it's better trying to rewrite the code that it will work on Ubuntu 20 and 22.

Maybe i could try to remove the password part (python passlib) and change it to manually adding a password.
Or if anyone are interested to help me to fix the scripts, i could share login data for a temp vps.

**Comment by Publish3r** [comment]
I forked another project and it's working very good.
In future please use that: https://github.com/Publish3r/SniDust-Telerising
